travis:
  secure:
    BINSTAR_TOKEN: Z391HXP4fOf9yMOt66SL8KjR3IWcOqzIkRoDXJ9YNd8y0uR9ygxao2Ahw3BkzMhf9mPD2hwuOfNLfv5UY0uLlrC3bjDra1Mh9fLoKcp57GbU2iOQn/A7fl6CvjQxsLa0Xzl45croI+aoslFYzAa91MTAvWCAzXIeUSBTDCz51GaSL9Zy6qpzVw3ui1sAfy+xMdNWHeQgT0fF0lMdk51KqnE7FILQAe2WG7Ye94IMYMssa4FoqPEjBGv9VbRakH8YKXn1gtUFJleNOx045syZsDpfgJu53dpCqIQ0WmOWqOa543lEXibZJFHJCRwTjNmilAOMCVfTOlOqH9KCJpF1VS63jiuHK6rMGRshcJrFM+T7gmaIxqbZfZorcS8F0kUc3N4jhcYONfSnMZUh74klw0yFjiTvigjWSRKytASnkAGFzBxZX70DPs9a1dGeh7e3oXnDdOna4ip+YHDZhVZdQHA9qAtsQEzo3csZN7f9KhoyaL8DPhUVVxx3hlW1DivrTw6XkPnsSlay1EevVfqvQdJGyQvBInnmkGJB8Gntalm5iykFtVt/Vp06W816MdiH6ItprHXwg5Bs2zWFEcaNPxApIitE8WmzjymeK3uF4cUHc3bCpzN5dvQEciS+vo1tv4rako4JyGa3vJjeDnc4scgTGRd9OVbZeyg8XeePurg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
